### PR TITLE
코드 수정 및 get_origin_patch, set_origin_patch 완성

### LINKED ISSUE #10: BoundingBox.py 구현
이미지를 캡쳐했으니깐 다시 붙여야겠지요?

### PR DESCRIPTION
**Pull request by jinwoo1225**

### CODE REVIEW

**Comment by jinwoo1225** [comment]
iu2
**원본 이미지**

test0
BoundingBox 파악

processed
Stub로 processed.jpg생성
test2
get_origin_patch
test3
set_origin_patch

**Comment by HkGdgg** [comment]
excuse me, I am interested in the baldgan part, I successfully run the project, but the result picture size is changed to 256x256, only the face of the person. So, I want to know how to apply the baldgan function but the result is the original picture size. How I change the test code here https://github.com/2021-HKNU-CD/HAiR/pull/31 , I am new in Python Langauge. Sorry, I don't understand korean.

**Comment by jinwoo1225** [comment]
@HkGdgg
 for first thanks for having interest in our project! but if you want to have original picture with `baldgan-enabled` picture you could use our `Scaler`, `BoundingBox` and `Aligner` component.

`
Orignal Picture --> BoundingBox.getOriginPatch() --(picture only with the face of image will come)--> AlignerWing.alignFoward() --(aligned image)--> Scaler --(Scaled Image of 256 * 256)--> BaldGAN.goBald() --(balded image of 256 * 256)--> Scaler --(Scale image to original Aligned image)--> AlignerWing.alignBackward() --(misaligned image(original state)) --> BouningBox.setOriginPatch ----> original image
`

### This image is demographic of our project



In your request to make original image with bald-state of hair, we have to
1. take face from image
2. align it to center
3. scale the image to 256 * 256 to use it in baldGAN or MichiGAN(Why? this model trained by `wing-aligned` and low resolution of 256 * 256 image)
4. transform it! by baldGAN
5. misalign it to original state
6. back the transformed image to original space
스크린샷 2022-01-10 오전 12 11 17

if you want close support you can add jinwoo17962@gmail.com to your google calendar to create google meet session. I'm happy to support your work! 😀

**Comment by HkGdgg** [comment]
@jinwoo1225 
Sorry, I am a beginner of the language, I understand your flow, but I am not sure about the syntax of step 5 - step 6.

image

step 1 to step 4 is based on the test code that you have provided here https://github.com/2021-HKNU-CD/HAiR/pull/31

For step 5 
I first scale the 256x256 baldgan-enabled picture back using **_scale_backward()_**, then I _**align_backward()**_ it. I am not sure my code here is correct or not.

But for step 6, I just use _**img = BB.set_origin_patch(BB.get_origin_patch())**_, it returns the original size of the picture but without baldgan-enable. What should I change in my code in order to get the original size of baldgan-enable picture

**Comment by jinwoo1225** [comment]
@HkGdgg you should put baldgan-enabled image to BB.set_origin_patch(baldgan-enabled-image)

**Comment by HkGdgg** [comment]
@jinwoo1225 Thank you!!! I finally got it. But I have another question or opinion.
image
image 1: 256x256 baldgan-enable picture
image 2:  _**scale_backward()**_
image 3:  _**scale_backward()**_ and _**align_backward()**_
image 4: _**BB.set_origin_patch()**_ 

After using **_BB.set_origin_patch()_**, we can get the original size of baldgan-enable picture, but the face part is not clear. I understand that because we first chop it to 256x256, then we scale it back which leads to the issue. 
But in image 3, we can see that after we use _**align_backward()**_ , the boundary has been chopped. It is because it has a rotation. So, the problem is the gap between bald hair and the boundary is smaller than before. After we use _**BB.set_origin_patch()**_  to get back the original size, we can see that some of the original hair is still here.
Here is another example:
image


Whatsoever, Thanks a lot for the help. This project is very nice!!

**Comment by jinwoo1225** [comment]
@HkGdgg I think this problem originated from using [wing.py](https://github.com/protossw512/AdaptiveWingLoss)(it create a normal distributed face of human to suitable to used in model).

**Comment by WooSeob** [comment]
@HkGdgg in AlignerWing, align tasks perform based on facial landmarks of input. therefore. for some inputs(ex. big hair shape) may not work well. its limit of our project 😅. Thank you for your interest in our project.

**Pull request merged**
